name: Weekly run to create export of select unrendered spatial datasets from Analyze Boston
on: 
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  nightly-download-allmaps-annotations:
    name: Write datasets to spatial-data-preservation/
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use cURL to download
        run: |-
          
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Analyze Boston snapshot: ${timestamp}" || exit 0
          git push
